export interface ServicioPayload {
  id: number;
  canalComunicacionId: number | null;
  fo_Sucursal_otorgante_Id: number;
  fo_Sucursal_Origen_Id: number;
  fo_Contrato: string;
  fo_Nombre_Titular: string;
  fo_Nombre_Finado: string;
  fo_Documento_Cliente_Id: number;
  fo_Documento_Cliente_url: string;
  fo_Monto_Devuelto: string | number;
  fo_Monto_devuelto_documento_url: string;
  fo_Jefe_Turno_Nombre: string;
  fo_Jefe_Turno_Puesto: string;
  fo_Jefe_Turno_WhatsApp: string;
  fo_Fecha_Servicio: string;
  fori_Status_Contrato_Id: number;
  fori_Saldo_Contrato: string | number;
  fori_Acepta_Convenio: boolean;
  fori_Otorga_Info_Nombre: string;
  fori_Otorga_Info_Puesto: string;
  fori_Otorga_Info_Telefono: string;
  fo_Contrato_Monto_Recuperado: string | number;
  fo_Contrato_Monto_Convenio: string | number;
  fo_Tipo_Servicio_Id: number;
  fo_Concepto_Id: number;
  exp_Solicitud_Servicio_Status_id: number;
  exp_Solicitud_Servicio_url: string;
  exp_Comprobante_Pago_Status_Id: number;
  exp_Comprobante_Pago_url: string;
  exp_Convenio_Status_Id: number;
  exp_Convenio_url: string;
  exp_Enviado_Grupo_Whats: boolean;
  exp_Motivo_De_No_Otorgado_Id: number | null;
  exp_Expediente_Completo: string;
  exp_Observaciones_cierre: string;
  exp_ine_responsable_url: string;
  exp_comprobante_domicilio_resp_url: string;
  exp_ine_aval_url: string;
  fori_estado_cuenta_url: string;
  penalizado: boolean;
  Usuario_CapturaId: number;
  Fecha_Captura: string;
  status: string;

  // Relations (optional as they come from GET but not POST)
  sucursalOtorgante?: any;
  sucursalOrigen?: any;
  tipoDocumento?: any;
  statusContrato?: any;
  tipoServicio?: any;
  concepto?: any;
  solicitudServicioStatus?: any;
  comprobantePagoStatus?: any;
  convenioStatus?: any;
  motivoNoOtorgado?: any;
  usuarioCaptura?: any;
  logs?: { usuarioId: number }[];
}

export interface ServicioCreatePayload {
  canalComunicacionId: number | null;
  fo_Sucursal_otorgante_Id: number;
  fo_Sucursal_Origen_Id: number;
  fo_Contrato: string;
  fo_Nombre_Titular: string;
  fo_Nombre_Finado: string;
  fo_Documento_Cliente_Id: number;
  fo_Documento_Cliente_url: string;
  fo_Monto_devuelto_documento_url: string;
  fo_Jefe_Turno_Nombre: string;
  fo_Jefe_Turno_Puesto: string;
  fo_Jefe_Turno_WhatsApp: string;
  fo_Fecha_Servicio: string;
  fori_Status_Contrato_Id: number;
  fori_Saldo_Contrato: number;
  fori_Acepta_Convenio: boolean;
  fori_Otorga_Info_Nombre: string;
  fori_Otorga_Info_Puesto: string;
  fori_Otorga_Info_Telefono: string;
  fo_Contrato_Monto_Recuperado: number;
  fo_Contrato_Monto_Convenio: number;
  fo_Monto_Devuelto: number;
  fo_Tipo_Servicio_Id: number;
  fo_Concepto_Id: number;
  exp_Solicitud_Servicio_Status_id: number;
  exp_Solicitud_Servicio_url: string;
  exp_Comprobante_Pago_Status_Id: number;
  exp_Comprobante_Pago_url: string;
  exp_Convenio_Status_Id: number;
  exp_Convenio_url: string;
  exp_Enviado_Grupo_Whats: boolean;
  exp_Motivo_De_No_Otorgado_Id: number | null;
  exp_Expediente_Completo: string;
  exp_Observaciones: string;
  exp_ine_responsable_url?: string;
  exp_comprobante_domicilio_resp_url?: string;
  exp_ine_aval_url?: string;
  fori_estado_cuenta_url?: string;
  status?: string;
}
